---

- name: update repository index
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install apaches package
  become: true
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu"