Vagrant.configure("2") do |config|

  config.vm.define "serverpgsql" do |serverpgsql|

    serverpgsql.vm.box = "generic/ubuntu2204"

    serverpgsql.vm.box_check_update = false

    serverpgsql.vm.network "forwarded_port", guest: 80, host: 80

    serverpgsql.vm.network "forwarded_port", guest: 8080, host: 8080

    serverpgsql.vm.network "private_network", ip: "192.168.33.10"

    serverpgsql.vm.synced_folder "./dockermanifest", "/opt/docker/dockermanifest"

    serverpgsql.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "serverpgsql"
      vb.memory = 2048
      vb.cpus = 2
    end

    serverpgsql.vm.provision "shell", path: "install-docker.sh"
  end

end
