Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  config.vm.box_check_update = false

  node.vm.hostname = "webserver"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "forwarded_port", guest: 3306, host: 3307

  config.vm.network "forwarded_port", guest: 25, host: 27

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "./siteweb", "/opt/tomcat/webapp"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "bootcamp4-webserver"
    vb.cpus = 1
    vb.memory = 1024
  end
end
