Vagrant.configure("2") do |config|

  config.vm.define "ansibleclt" do |ansibleclient|
  
    ansibleclient.vm.box = "bento/ubuntu-22.04"
    ansibleclient.vm.hostname = "client"
    ansibleclient.vm.box_check_update = false

    ansibleclient.vm.network "forwarded_port", guest: 80, host: 80
    ansibleclient.vm.network "forwarded_port", guest: 8080, host: 8080
    ansibleclient.vm.network "forwarded_port", guest: 3306, host: 3306

    ansibleclient.vm.network "private_network", type: "static", ip: "192.168.0.11"

    ansibleclient.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "ansibleclt"
      vb.memory = 1024
      vb.cpus = 1
    end
  end


  config.vm.define "ansiblesrv" do |ansibleserver|
  
    ansibleserver.vm.box = "bento/ubuntu-22.04"

    ansibleserver.vm.box_check_update = false

    ansibleserver.vm.hostname = "server"

    ansibleserver.vm.network "private_network", type: "static", ip: "192.168.0.10"

    ansibleserver.vm.synced_folder "./ansible-workspace", "/playbooks"
    ansibleserver.vm.synced_folder "./key", "/home/vagrant/.ssh/"

    ansibleserver.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "ansiblesrv"
      vb.memory = 1024
      vb.cpus = 1
    end

    ansibleserver.vm.provision "shell", path: "install-ansible.sh"
    ansibleserver.vm.provision "shell", path: "provisionning-with-ansible.sh"
  end
end
